name = "todolist-app"
main = "src/index.js"
compatibility_date = "2023-09-04"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
binding = "EXAMPLE_TODOS"
id = "644a4a7ab96d4766a957844426e36a15"
preview_id = "47f38f717d2c4d8cb5c1fad40f720f88"